# Generated by Django 3.1.1 on 2020-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('u_subject', models.CharField(max_length=100)),
                ('u_description', models.CharField(max_length=300)),
            ],
        ),
    ]
