# Generated by Django 3.1.1 on 2020-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muneebulhassan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_link', models.CharField(max_length=100)),
                ('p_description', models.CharField(max_length=300)),
            ],
        ),
    ]
