# Generated by Django 3.1.1 on 2020-09-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muneebulhassan', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
