# Generated by Django 3.1.1 on 2020-09-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muneebulhassan', '0004_auto_20200920_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=30)),
                ('e_post', models.CharField(max_length=50)),
                ('e_startdate', models.CharField(max_length=30)),
                ('e_enddate', models.CharField(max_length=30)),
            ],
        ),
    ]
