# Generated by Django 3.1.1 on 2020-09-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muneebulhassan', '0005_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiencedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_detail', models.CharField(max_length=100)),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='muneebulhassan.experience')),
            ],
        ),
    ]
