# Generated by Django 3.1.1 on 2020-09-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muneebulhassan', '0006_experiencedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect',
            old_name='u_description',
            new_name='u_email',
        ),
    ]
